version: "3"
services:
  elasticsearch:
    container_name: es01
    image: elasticsearch:8.0.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: kibana:8.0.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTs=https://es01:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

  # logstash:
  #   image: logstash:8.0.0
  #   ports:
  #     - 5044:5044
  #     - 9600:9600
  #     - 9700:9700
networks:
  elastic:
    driver: bridge
  